name: ai-playbook
channels:
  - anaconda
  - conda-forge
  - omnia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - absl-py=0.9.0
  - asn1crypto=1.3.0
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - blinker=1.4
  - bzip2=1.0.8
  - c-ares=1.15.0
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.1
  - cryptography=2.8
  - dbus=1.13.12
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.56.2
  - gmp=6.1.2
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.4
  - icu=58.2
  - idna=2.9
  - importlib_metadata=1.3.0
  - intel-openmp=2020.0
  - ipykernel=5.1.3
  - ipython=7.11.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.15.2
  - jinja2=2.10.3
  - jpeg=9b
  - json5=0.8.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=6.0.0
  - jupyter_core=4.6.1
  - jupyterlab=1.2.6
  - jupyterlab_code_formatter=1.0.3
  - jupyterlab_server=1.0.6
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - libffi=3.2.1
  - libpng=1.6.37
  - libprotobuf=3.11.4
  - libsodium=1.0.16
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - line_profiler=2.1.2
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - more-itertools=8.0.2
  - nbconvert=5.6.1
  - nbformat=4.4.0
  - ncurses=6.1
  - nodejs=11.14.0
  - notebook=6.0.2
  - oauthlib=3.1.0
  - openssl=1.1.1
  - opt_einsum=3.1.0
  - packaging=20.1
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.2
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - pyasn1=0.4.8
  - pycparser=2.20
  - pygments=2.5.2
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - pyrsistent=0.15.6
  - pysocks=1.7.1
  - python=3.7.1
  - python-dateutil=2.8.1
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtconsole=4.6.0
  - readline=7.0
  - requests=2.23.0
  - requests-oauthlib=1.3.0
  - rsa=4.0
  - scipy=1.4.1
  - send2trash=1.5.0
  - setuptools=45.1.0
  - sip=4.19.13
  - sqlite=3.28.0
  - tensorflow-estimator=2.1.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.0.3
  - traitlets=4.3.3
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - xz=5.2.4
  - yapf=0.28.0
  - zeromq=4.3.1
  - zipp=0.6.0
  - zlib=1.2.11
  - pip:
      # - _openmp_mutex==4.5
      # - _tflow_select==2.1.0
      - alive-progress==1.6.2
      - appdirs==1.4.4
      - astor==0.8.1
      - astroid==2.3.3
      - audioread==2.1.9
      - box2d==2.3.10
      - cachetools==4.1.0
      - cloudpickle==1.2.2
      - colorama==0.4.3
      # - cudnn==7.6.5
      # - cudatoolkit==10.1.24
      # - cupti==10.1.168
      - cycler==0.10.0
      - dataclasses==0.6
      - fire==0.3.1
      - future==0.18.2
      - gast==0.2.2
      - google-auth==1.14.1
      - grpcio==1.28.1
      - gym==0.15.4
      - imageio==2.9.0
      - imageio-ffmpeg==0.4.3
      - isort==4.3.21
      - joblib==1.0.0
      - kiwisolver==1.1.0
      - lazy-object-proxy==1.4.3
      # - libgcc-ng==9.2.0
      - libgomp==9.2.0
      - libgfortran-ng==7.3.0
      - librosa==0.8.0
      - libstdcxx-ng==9.2.0
      - llvmlite==0.35.0
      - markdown==3.2.1
      - matplotlib==3.3.0
      - mccabe==0.6.1
      - moviepy==1.0.3
      - nbdime==2.0.0
      - numba==0.52.0
      - numpy==1.18.1
      - opencv-python==4.1.2.30
      - opt-einsum==3.2.1
      - pandas==1.1.3
      - pillow==7.0.0
      - pluggy==0.13.1
      - pooch==1.3.0
      - proglog==0.1.9
      - protobuf==3.11.3
      - py==1.8.1
      - pyasn1-modules==0.2.8
      - pygame==2.0.0
      - pyglet==1.3.2
      - pylint==2.4.4
      - pytest==5.4.3
      - pytz==2020.1
      - resampy==0.2.2
      - scikit-learn==0.24.0
      - six==1.14.0
      - soundfile==0.10.3.post1
      - tensorboard==2.1.1
      - tensorflow==2.1.0
      - tensorflow-base==2.1.0
      - tensorflow-gpu==2.1.0
      - termcolor==1.1.0
      - threadpoolctl==2.1.0
      - torch==1.7.0
      - torchvision==0.8.1
      - tqdm==4.43.0
      - typed-ast==1.4.1
      - urllib3==1.25.9
      - wrapt==1.11.2

